services:
  mainapi:
    image: mainapi
    build:
      context: Backend
      dockerfile: MainApi/Dockerfile
    ports:
      - "5200:8080"
    depends_on:
      - postgres
      - mongo
      - rabbitmq
  
  postgres:
    image: postgres:alpine
    hostname: postgres
    environment:
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: someDatabase
  
  mongo:
    image: mongo
    hostname: mongo
    restart: always
    volumes:
      - ~/apps/Spotify/mongo/data:/data/db
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3-alpine
    hostname: rabbitmq
    restart: always
    ports:
      - "5643:5643"